# Site settings
title: Driven Software
# email:
description: "Driven Software Website"
baseurl: ""
url: 
twitter_username: DrivenSoftware
github_username: DrivenSoftware

# Build settings
# markdown: kramdown
permalink: pretty

poole:
  default_extension: "markdown"

markdown: rdiscount
highligher: pygments
# pygments: true
# ftp_host: ftp.drivensoftware.net
# ftp_dir: /


exclude: [node_modules, package.json, bower_components, bower.json]
